name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/guides/

  
  fonts:
    - family: Italiana
      fonts:
        - asset: assets/fonts/Italiana-Regular.ttf
    
    - family: GL Nummernschild
      fonts:
        - asset: assets/fonts/GL-Nummernschild-Eng.ttf


        
        
  